const productsActionsTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  SORT_FILTERED_PRODUCTS: 'SORT_FILTERED_PRODUCTS',
  PRODUCT_FILTER_RESET: 'PRODUCT_FILTER_RESET',
};

export default productsActionsTypes;
