const productsActionsTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCTS_IS_FETCHING: 'SET_PRODUCTS_IS_FETCHING',
  SET_PRODUCTS_CURRENT_PAGE: 'SET_PRODUCTS_CURRENT_PAGE',
  SET_PRODUCTS_FETCH_ERROR: 'SET_PRODUCTS_FETCH_ERROR',

  ADD_PRODUCT: 'ADD_PRODUCT',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  SORT_FILTERED_PRODUCTS : 'SORT_FILTERED_PRODUCTS',
  PRODUCT_FILTER_RESET: 'PRODUCT_FILTER_RESET'
};

export default productsActionsTypes;
